/**
 * actionTypes Created by sprouts
 */

const actionTypes = {
	GET_ARTICLE_LIST: "GET_ARTICLE_LIST",
	HANDLE_FAILURE: "HANDLE_FAILURE",
	GET_HOME_BANNER: "GET_HOME_BANNER",
	GET_ARTICLE_LIST_MORE: "GET_ARTICLE_LIST_MORE",
	GET_SYSTEM_LIST: "GET_SYSTEM_LIST",
	GET_SYSTEM_OF_ARTICLE_LIST: "GET_SYSTEM_OF_ARTICLE_LIST",
	GET_SYSTEM_OF_ARTICLE_LIST_MORE: "GET_SYSTEM_OF_ARTICLE_LIST_MORE",

}

export default actionTypes;
