/**
 * actionTypes Created by sprouts
 */

const actionTypes = {
	GET_ARTICLE_LIST: "GET_ARTICLE_LIST",
	HANDLE_FAILURE: "HANDLE_FAILURE",
	GET_HOME_BANNER: "GET_HOME_BANNER",
	GET_ARTICLE_LIST_MORE: "GET_ARTICLE_LIST_MORE",
	GET_SYSTEM_LIST: "GET_SYSTEM_LIST",
	GET_SYSTEM_OF_ARTICLE_LIST: "GET_SYSTEM_OF_ARTICLE_LIST",
	GET_SYSTEM_OF_ARTICLE_LIST_MORE: "GET_SYSTEM_OF_ARTICLE_LIST_MORE",
	GET_WX_ARTICLE_LIST: "GET_WX_ARTICLE_LIST",
	ARTICLE_LOADING: "ARTICLE_LOADING",
	GET_PROJECT_TREE: "GET_PROJECT_TREE",
	GET_GUIDE_TREE: "GET_GUIDE_TREE",
	UPDATE_SELECT_INDEX: "UPDATE_SELECT_INDEX"
}

export default actionTypes;
